name: CI + CD

on:
  push:
    paths-ignore:
      - '**.md'
      - '.vscode/**'
      - 'docs/**'
      - 'examples/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/dev/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: localhost:5000/crl-dev:local-test

      - name: Run Tests
        uses: addnab/docker-run-action@v3
        with:
          image: localhost:5000/crl-dev:local-test
          shell: bash
          run: |
            cd /crl/test
            source /ros_entrypoint.sh
            python3 -m pytest -x -s -v

      - name: Login to DockerHub
        if: success() && github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: cakerobotics
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        if: success() && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/dev/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: cakerobotics/crl-dev:latest

      - name: Login to On-site Registry
        if: success() && github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: oreg.cakerobotics.com
          username: cakerobotics
          password: ${{ secrets.OREG_TOKEN }}

      - name: Push to On-site Registry
        if: success() && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/dev/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: oreg.cakerobotics.com/crl-dev:latest
