# From: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
# See also: https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching

name: test

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: test/Dockerfile
          push: false
          tags: crl:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
