name: Test

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          image: ros:galactic-ros-base-focal
          options: -v ${{ github.workspace }}:/crl
          run: |
            cd /crl
            pip3 install .
            python3 -m pytest
